format = "$directory$git_branch$git_status$character"
add_newline = false

[character]
format = "[⮞ ](bold green)"
error_symbol = "[✖](bold red) "

[directory]
truncation_length = 2
format = "[$path|](dimmed blue)"

[git_branch]
symbol = " "
style = "bold purple"
format = " [$symbol$branch]($style)"

[git_commit]
commit_hash_length = 6
style = "bold white"

[git_status]
format = '[\[$all_status\]](dimmed purple) '
conflicted = "[☇ ](bold red)"
stashed = "[⚿ ](bold 214)"
modified = "[🗎 ](bold yellow)"
staged = "[✚ ](bold green)"
ahead = ""
behind = ""
diverged = ""
up_to_date = ""
untracked = ""
renamed = ""
deleted = ""
typechanged = ""
